---
openapi: "3.0.0"
info:
  title: "Events API"
  version: "1.0.0"
  description: "API for managing timeline events."
  license:
    name: "MIT"
    url: "https://opensource.org/licenses/MIT"
servers:
- url: "https://spaces-api.example.com"
  description: "Production API Server"
security:
- ApiKeyAuth: []
paths:
  /events:
    get:
      summary: "Get all events"
      operationId: "getEvents"
      security:
      - ApiKeyAuth: []
      responses:
        "200":
          description: "A list of events"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Event"
        "400":
          description: "Bad request"
        "401":
          description: "Unauthorized"
    post:
      summary: "Create a new event"
      operationId: "createEvent"
      security:
      - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Event"
      responses:
        "201":
          description: "Event created"
        "400":
          description: "Bad request"
        "401":
          description: "Unauthorized"
components:
  securitySchemes:
    ApiKeyAuth:
      type: "apiKey"
      in: "header"
      name: "X-API-Key"
  schemas:
    Event:
      type: "object"
      required:
      - "title"
      - "date"
      properties:
        id:
          type: "integer"
          format: "int64"
        title:
          type: "string"
        description:
          type: "string"
          nullable: true
        date:
          type: "string"
          format: "date-time"
        category:
          type: "string"
          nullable: true
        imageUrl:
          type: "string"
          nullable: true
